---
- name: Install system python
  become: yes
  package:
    name: "{{ item }}"
    state: present
  register: result
  retries: 3
  until: result is succeeded
  with_items: "{{ system_python_packages }}"

- name: Install pip packages into system python
  pip:
    name: "{{ pip_packages }}"
    extra_args: --user
  environment:
      PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
